# Generated by Django 5.2.1 on 2025-10-09 03:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('codigo', models.CharField(max_length=2, unique=True)),
            ],
            options={
                'ordering': ('codigo',),
            },
        ),
        migrations.CreateModel(
            name='Estrategia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sig', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='ID deve seguir o padrão FaB001-1d21d, IgD001-3s03s etc.', regex='^[A-Z][a-z][BDA]\\d{3}-[13]\\w\\d{2}[sd]$')])),
                ('dimensao', models.CharField(choices=[('Básico', 'Básico'), ('Desafio', 'Desafio'), ('Avançado', 'Avançado')], max_length=10)),
                ('estrategia', models.TextField()),
                ('frequencia', models.CharField(max_length=30)),
                ('periodo', models.CharField(max_length=30)),
                ('freq_codigo', models.CharField(max_length=3)),
                ('periodo_codigo', models.CharField(max_length=4)),
                ('peso', models.PositiveSmallIntegerField(default=1)),
                ('ordem_area', models.PositiveSmallIntegerField(default=0)),
                ('ordem_dimensao', models.PositiveSmallIntegerField(default=0)),
                ('ordem_estrategia', models.PositiveSmallIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estrategias', to='projeto21.area')),
            ],
            options={
                'ordering': ('ordem_area', 'ordem_dimensao', 'ordem_estrategia'),
            },
        ),
    ]
