# Generated by Django 5.2.1 on 2025-10-26 20:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimensao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('peso', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='rascunho', max_length=12)),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_mentoria', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_vocacionais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-iniciado_em'],
            },
        ),
        migrations.CreateModel(
            name='Consentimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('aceito_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('revogado_em', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consentimento',
                'verbose_name_plural': 'Consentimentos',
                'ordering': ['-aceito_em'],
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('tipo', models.CharField(choices=[('likert', 'Likert 1–5'), ('single', 'Escolha única')], default='likert', max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('dimensao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='vocacional.dimensao')),
            ],
            options={
                'ordering': ['dimensao__nome', 'ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('valor', models.IntegerField(help_text='Pontuação desta opção para a dimensão')),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='vocacional.pergunta')),
            ],
            options={
                'ordering': ['pergunta', 'ordem', 'id'],
                'unique_together': {('pergunta', 'ordem')},
            },
        ),
        migrations.CreateModel(
            name='Progresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progresso',
                'verbose_name_plural': 'Progressos',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(default=0)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='vocacional.avaliacao')),
                ('opcao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vocacional.opcao')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocacional.pergunta')),
            ],
            options={
                'ordering': ['pergunta__ordem', 'pergunta_id'],
                'unique_together': {('avaliacao', 'pergunta')},
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.IntegerField(default=0)),
                ('percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('nivel', models.CharField(blank=True, help_text='Ex.: baixo, médio, alto', max_length=40)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='vocacional.avaliacao')),
                ('dimensao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocacional.dimensao')),
            ],
            options={
                'ordering': ['-pontuacao'],
                'unique_together': {('avaliacao', 'dimensao')},
            },
        ),
    ]
