# Generated by Django 5.2.1 on 2025-10-27 01:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocacional', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestaoGuia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('enunciado', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('likert', 'Likert 1-5'), ('texto', 'Texto')], default='likert', max_length=12)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoGuia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('concluida', 'Concluída')], default='rascunho', max_length=10)),
                ('aceite_termos', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avaliação do Guia',
                'verbose_name_plural': 'Avaliações do Guia',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='RespostaGuia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(blank=True, null=True)),
                ('texto', models.TextField(blank=True, default='')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='vocacional.avaliacaoguia')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocacional.questaoguia')),
            ],
            options={
                'unique_together': {('avaliacao', 'questao')},
            },
        ),
    ]
