# Generated by Django 5.2.1 on 2025-10-27 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocacional', '0002_questaoguia_avaliacaoguia_respostaguia'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='ordem_qids',
            field=models.TextField(blank=True, default=''),
        ),
    ]
