# Generated by Django 5.2.1 on 2025-10-27 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocacional', '0003_avaliacao_ordem_qids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='ordem_qids',
            new_name='ordem_ids',
        ),
    ]
