# Generated by Django 5.2.1 on 2025-11-07 04:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocacional', '0004_rename_ordem_qids_avaliacao_ordem_ids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='avaliacaoguia',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_avaliacao_guia_por_user'),
        ),
    ]
