# Generated by Django 5.2.1 on 2025-11-11 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocacional', '0005_unica_avaliacao_guia_por_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consentimento',
            old_name='ativo',
            new_name='aceito',
        ),
    ]
