# Generated by Django 5.2.1 on 2025-11-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocacional', '0006_rename_ativo_consentimento_aceito'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='email_enviado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='whatsapp_enviado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
