# Generated by ChatGPT patch (Refinamento Top 3)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocacional", "0007_avaliacao_email_enviado_em_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dimensao",
            name="codigo",
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="pergunta",
            name="codigo",
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="pergunta",
            name="invert",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pergunta",
            name="bloco",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="avaliacao",
            name="passe_atual",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="avaliacao",
            name="ref_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
