# Generated by Django 5.0.2 on 2026-02-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocacional', '0009_guia_questionario_v1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questaoguia',
            name='codigo',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='questaoguia',
            name='opcoes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='questaoguia',
            name='tipo',
            field=models.CharField(choices=[('radio', 'Radio'), ('multi', 'Múltipla escolha'), ('likert', 'Likert 1-5'), ('texto', 'Texto'), ('nota10', 'Nota 0-10'), ('nps', 'NPS 0-10')], default='likert', max_length=12),
        ),
    ]
