# Generated by ChatGPT patch
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocacional", "0010_alter_questaoguia_codigo_alter_questaoguia_opcoes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="avaliacao",
            name="fluxo",
            field=models.CharField(
                choices=[("bonus75", "Bônus 75"), ("ref", "Refinamento")],
                db_index=True,
                default="bonus75",
                max_length=12,
            ),
        ),
    ]
