# Generated by Django 5.0.2 on 2026-04-22 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocacional', '0011_avaliacao_fluxo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ['-iniciado_em'], 'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
    ]
