# Generated by Django 5.2.1 on 2025-09-07 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicial', models.CharField(choices=[('F', 'Família'), ('I', 'Igreja'), ('E', 'Escola'), ('A', 'Amigos'), ('C', 'Comunidade'), ('M', 'Eu mesmo')], max_length=1, unique=True)),
                ('nome', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
            },
        ),
        migrations.CreateModel(
            name='Estrategia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=180)),
                ('codigo', models.SlugField(max_length=80, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('nivel', models.CharField(choices=[('B', 'Básico'), ('D', 'Desafio'), ('A', 'Avançado')], default='B', max_length=1)),
                ('ordem_nivel', models.PositiveSmallIntegerField(default=1)),
                ('dificuldade', models.PositiveSmallIntegerField(default=1)),
                ('pontos', models.PositiveSmallIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estrategias', to='sonho_de_ser.area')),
            ],
            options={
                'ordering': ['area__inicial', 'nivel', 'ordem_nivel', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Mentoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pode_ver_registros', models.BooleanField(default=True)),
                ('pode_criar_anotacoes', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('consentido_em', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorias_como_mentor', to=settings.AUTH_USER_MODEL)),
                ('mentorado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorias_recebidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnotacaoMentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('texto', models.CharField(max_length=500)),
                ('visivel_para_aluno', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotacoes', to='sonho_de_ser.mentoria')),
            ],
        ),
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('Professor', 'Professor'), ('Responsável', 'Responsável'), ('Líder', 'Líder religioso'), ('Parente', 'Parente'), ('Outro', 'Outro')], max_length=16)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('estrategia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonho_de_ser.estrategia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_diarios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='estrategia',
            constraint=models.UniqueConstraint(fields=('area', 'nivel', 'ordem_nivel'), name='unq_area_nivel_ordem'),
        ),
        migrations.AddConstraint(
            model_name='mentoria',
            constraint=models.UniqueConstraint(fields=('mentor', 'mentorado'), name='unique_mentoria_par'),
        ),
        migrations.AddConstraint(
            model_name='registrodiario',
            constraint=models.UniqueConstraint(fields=('usuario', 'data', 'estrategia'), name='uniq_registro_por_usuario_data_estrategia'),
        ),
    ]
