# Generated by Django 5.2.1 on 2025-10-09 03:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicial', models.CharField(choices=[('F', 'Família'), ('I', 'Igreja'), ('E', 'Escola'), ('A', 'Amigos'), ('C', 'Comunidade'), ('M', 'Eu mesmo')], max_length=1, unique=True)),
                ('nome', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
            },
        ),
        migrations.CreateModel(
            name='Estrategia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=180)),
                ('codigo', models.SlugField(max_length=80, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('nivel', models.CharField(choices=[('B', 'Básico'), ('D', 'Desafio'), ('A', 'Avançado')], default='B', max_length=1)),
                ('ordem_nivel', models.PositiveSmallIntegerField(default=1)),
                ('dificuldade', models.PositiveSmallIntegerField(default=1)),
                ('pontos', models.PositiveSmallIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estrategias', to='sonho_de_ser.area')),
            ],
            options={
                'ordering': ['area__inicial', 'nivel', 'ordem_nivel', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Mentoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pode_ver_registros', models.BooleanField(default=True)),
                ('pode_criar_anotacoes', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('consentido_em', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ATIVA', 'Ativa'), ('PAUSADA', 'Pausada'), ('ENCERRADA', 'Encerrada')], db_index=True, default='ATIVA', max_length=10)),
                ('aceita_pelo_mentorado_em', models.DateTimeField(blank=True, null=True)),
                ('revogada_em', models.DateTimeField(blank=True, null=True)),
                ('escopo', models.CharField(choices=[('PROJ21', 'Projeto 21'), ('VOCAC', 'Vocacional'), ('CURSO', 'Curso/Acadêmico'), ('OUTRO', 'Outro')], db_index=True, default='PROJ21', max_length=10)),
                ('observacoes', models.TextField(blank=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorias_como_mentor', to=settings.AUTH_USER_MODEL)),
                ('mentorado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorias_recebidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ativo', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AnotacaoMentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('texto', models.CharField(max_length=500)),
                ('visivel_para_aluno', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotacoes', to='sonho_de_ser.mentoria')),
            ],
        ),
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('Professor', 'Professor'), ('Responsável', 'Responsável'), ('Líder', 'Líder religioso'), ('Parente', 'Parente'), ('Outro', 'Outro')], max_length=16)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('ativo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_p21', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ativo', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PlanoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('estrategia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_incluindo', to='sonho_de_ser.estrategia')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='sonho_de_ser.plano')),
            ],
            options={
                'ordering': ['estrategia__area__inicial', 'estrategia__nivel', 'estrategia__ordem_nivel', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('estrategia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonho_de_ser.estrategia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_diarios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='estrategia',
            constraint=models.UniqueConstraint(fields=('area', 'nivel', 'ordem_nivel'), name='unq_area_nivel_ordem'),
        ),
        migrations.AddIndex(
            model_name='mentoria',
            index=models.Index(fields=['mentor', 'ativo'], name='sonho_de_se_mentor__7d299d_idx'),
        ),
        migrations.AddIndex(
            model_name='mentoria',
            index=models.Index(fields=['mentorado', 'ativo'], name='sonho_de_se_mentora_c32362_idx'),
        ),
        migrations.AddIndex(
            model_name='mentoria',
            index=models.Index(fields=['status'], name='sonho_de_se_status_2161d9_idx'),
        ),
        migrations.AddIndex(
            model_name='mentoria',
            index=models.Index(fields=['escopo'], name='sonho_de_se_escopo_fc64aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='mentoria',
            constraint=models.UniqueConstraint(fields=('mentor', 'mentorado'), name='unique_mentoria_par'),
        ),
        migrations.AddIndex(
            model_name='plano',
            index=models.Index(fields=['usuario', 'ativo'], name='sonho_de_se_usuario_7325c7_idx'),
        ),
        migrations.AddIndex(
            model_name='planoitem',
            index=models.Index(fields=['plano', 'ativo'], name='sonho_de_se_plano_i_afcf12_idx'),
        ),
        migrations.AddIndex(
            model_name='planoitem',
            index=models.Index(fields=['estrategia'], name='sonho_de_se_estrate_8c4316_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='planoitem',
            unique_together={('plano', 'estrategia')},
        ),
        migrations.AddConstraint(
            model_name='registrodiario',
            constraint=models.UniqueConstraint(fields=('usuario', 'data', 'estrategia'), name='uniq_registro_por_usuario_data_estrategia'),
        ),
    ]
