# Generated by Codex on 2026-04-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sonho_de_ser", "0002_jornada_diaria_e_status_registro"),
    ]

    operations = [
        migrations.AddField(
            model_name="estrategia",
            name="dosagem_texto",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="estrategia",
            name="frequencia_texto",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="estrategia",
            name="objetivo_codigo",
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name="estrategia",
            name="objetivo_descricao",
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name="estrategia",
            name="ordem_area",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="estrategia",
            name="ordem_dimensao",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="estrategia",
            name="periodo_texto",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
