# Generated by Codex on 2026-04-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sonho_de_ser", "0003_estrategia_objetivos_e_dosagem"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="estrategia",
            name="unq_area_nivel_ordem",
        ),
        migrations.AddConstraint(
            model_name="estrategia",
            constraint=models.UniqueConstraint(
                fields=("area", "nivel", "objetivo_codigo", "ordem_nivel"),
                name="unq_area_nivel_objetivo_ordem",
            ),
        ),
    ]
