# Generated by Codex on 2026-04-15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sonho_de_ser", "0004_ajusta_unicidade_estrategia_objetivo"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="estrategia",
            name="unq_area_nivel_objetivo_ordem",
        ),
    ]
