# Generated by Django 5.0.2 on 2026-04-22 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonho_de_ser', '0005_remove_unicidade_composta_estrategia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estrategia',
            options={'ordering': ['area__inicial', 'nivel', 'objetivo_codigo', 'ordem_nivel', 'titulo']},
        ),
        migrations.AlterField(
            model_name='area',
            name='inicial',
            field=models.CharField(choices=[('F', 'FamÃ\xadlia'), ('I', 'Igreja'), ('E', 'Escola'), ('A', 'Amigos'), ('C', 'Comunidade'), ('M', 'Eu mesmo')], max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='estrategia',
            name='nivel',
            field=models.CharField(choices=[('B', 'BÃ¡sico'), ('D', 'Desafio'), ('A', 'AvanÃ§ado')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='mentoria',
            name='escopo',
            field=models.CharField(choices=[('PROJ21', 'Projeto 21'), ('VOCAC', 'Vocacional'), ('CURSO', 'Curso/AcadÃªmico'), ('OUTRO', 'Outro')], db_index=True, default='PROJ21', max_length=10),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='papel',
            field=models.CharField(choices=[('Professor', 'Professor'), ('ResponsÃ¡vel', 'ResponsÃ¡vel'), ('LÃ\xadder', 'LÃ\xadder religioso'), ('Parente', 'Parente'), ('Outro', 'Outro')], max_length=16),
        ),
        migrations.AlterField(
            model_name='registrodiario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registrodiario',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
