# Generated by Django 5.2.1 on 2025-10-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NivelEvolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_nivel', models.CharField(max_length=255)),
                ('pontuacao_minima', models.IntegerField()),
                ('pontuacao_maxima', models.IntegerField()),
            ],
        ),
    ]
