# Generated by Django 5.2.1 on 2025-11-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('produto_slug', models.SlugField()),
                ('origem', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Acesso pendente',
                'verbose_name_plural': 'Acessos pendentes',
                'indexes': [models.Index(fields=['email', 'produto_slug'], name='core_pendin_email_34a0fa_idx')],
            },
        ),
    ]
