# Generated by Codex on 2026-04-16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_ajuste_core"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuiaPromotionalDelivery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("recipient_email", models.EmailField(max_length=254)),
                ("source", models.CharField(default="governanca_promocional", max_length=50)),
                ("status", models.CharField(choices=[("sent", "Enviado")], default="sent", max_length=20)),
                ("sent_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("attachment_name", models.CharField(blank=True, default="", max_length=255)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guia_promotional_deliveries_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guia_promotional_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Envio promocional do Guia",
                "verbose_name_plural": "Envios promocionais do Guia",
                "ordering": ["-sent_at", "-id"],
            },
        ),
    ]
