# Generated by Codex on 2026-04-16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_guiapromotionaldelivery"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutionalDemoAccess",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("institution_name", models.CharField(blank=True, default="", max_length=255)),
                ("source", models.CharField(default="governanca_demo", max_length=50)),
                ("starts_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("revoked_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="institutional_demo_accesses_granted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institutional_demo_accesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Acesso demo institucional",
                "verbose_name_plural": "Acessos demo institucionais",
                "ordering": ["-starts_at", "-id"],
            },
        ),
    ]
