# Generated by Django 5.0.2 on 2026-04-22 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_expand_instituicao_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicaousuario',
            name='papel',
            field=models.CharField(choices=[('contato_institucional', 'Contato administrativo/institucional'), ('contato_financeiro', 'Contato financeiro'), ('contato_academico', 'Contato academico'), ('aluno', 'Aluno'), ('mentor', 'Mentor'), ('funcionario', 'Funcionario'), ('orientador', 'Orientador'), ('membro', 'Membro')], db_index=True, default='membro', max_length=30),
        ),
    ]
