# Generated by Django 5.2.1 on 2025-11-04 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nome', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Acesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(default='organico', max_length=30)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos', to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos', to='contas.produto')),
            ],
            options={
                'verbose_name': 'Acesso a Produto',
                'verbose_name_plural': 'Acessos a Produtos',
                'indexes': [models.Index(fields=['user', 'produto'], name='contas_aces_user_id_7401e1_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('expires_at__isnull', True)), fields=('user', 'produto'), name='uniq_acesso_ativo_por_user_produto')],
            },
        ),
    ]
